### ISSUE TITLE
Can't find 'static' directory

### ISSUE THREAD

**Issue by bendub** [manatlan/guy#3] opened 2019-12-19 12:54 UTC
Hello manatlan,
I package an app using setuptools.
The app is installed in the user environment:

>     $ python3 -m pip install --user mypkg.tar.gz
My main script located in ~/.local/bin and the package itself is located in ~/.local/lib/python3.X/site-packages/MyPkg/.
When I execute my script, my browser returns a page containing:

>     ERROR: can't find /home/USER/.local/bin/static/APP.html

The directory 'static' is actually located in ~/.local/lib/python3.X/site-packages/MyPkg/ui/static.

Thank you

**Comment by manatlan** [comment] 2019-12-19 15:12
it's the same bug as #2 ;-)

**Comment by bendub** [comment] 2019-12-19 15:20
Two bugs resolved in one action \o/

**Comment by manatlan** [comment] 2020-01-24 09:14
In fact ... it's a lot more complex ...
I've made the "os.chdir()" (when server starts) to be sure to place the CWD where the 'exe' (freezed one) sits. (to be able to locate static & config.json).
It works very well ... on windows with freezed one ...
But it's not really adapted for people who wants to release pypi packages ...

How do you embed your files (setuptools with "package_data" ? or data_files)

For packaged one, I will need to deal with pkg_ressource ...

**Comment by bendub** [comment] 2020-01-24 09:23
Hello Manatlan,
I embed my files in a package using setuptools with "package_data":
```
package_data={
          '': ['ui/static/*.html',
               'ui/static/*.png']
      }
```

**Comment by manatlan** [comment] 2020-01-24 09:26
thks ...

and, to build your package : you did : 

     python3.7 setup.py sdist

?

**Comment by bendub** [comment] 2020-01-24 09:33
Yes, to be precise:
>python3 setup.py sdist bdist_wheel

**Comment by manatlan** [comment] 2020-01-24 09:47
I don't reach to include static files in my sdist tar.gz ;-(

**Comment by bendub** [comment] 2020-01-24 09:59
Could you use my tar.gz?

**Comment by manatlan** [comment] 2020-01-24 11:18
Can't reach to embbed static files ... perhaps you will see my trouble ?!
[test_app.zip](https://github.com/manatlan/guy/files/4108065/test_app.zip)

**Comment by manatlan** [comment] 2020-01-24 12:51
please, can you try that (replace your guy.py with this one
[guy.txt](https://github.com/manatlan/guy/files/4108503/guy.txt)
)... do you have got better result ?
(sorry, can't test here .. because can't reproduce)

**Comment by manatlan** [comment] 2020-01-25 12:48
> Could you use my tar.gz?

yes .. I could

**Comment by manatlan** [comment] 2020-01-25 16:56
First ... forgot all I said before ^^ ;-)

I've reach to embbed data in a package (bdist_wheel) ... using pthe marvelous "poetry" ;-)
And reach to reproduce exactly your problem !

Try this future version of guy [guy.txt](https://github.com/manatlan/guy/files/4112256/guy.txt)
(don't wanna to release yet ... because I should test on windows, with frozen exe (to be sure that there are no regression) ... I could test/release on monday evening)

Now ... guy doesn't change/enforce "current directory" (it's a lot better like that !) ... and it can see if it's executed from a python package ... and rewrite the good path to the data ! So now : you can build pypi package ;-)

In your case : perhaps you should change your static folder ... because it seems that you have prefixed it with "ui" (set `guy.FOLDERSTATIC = "ui/static"`) ...

BTW, it works, like a charm, for me ... using poetry to build my wheel ... in your case, with pure setuptools ... it should work too ... but not sure at 100%

BTW2 : I will add a page, in the docs, to explain how to embbed a guy app in a pypi package (using poetry only ... )

**Comment by manatlan** [comment] 2020-01-25 17:56
btw, the new tuto is here : https://guy-docs.glitch.me/howto_build_whl_package/

**Comment by manatlan** [comment] 2020-01-26 09:45
btw, i've comitted the 0.4.0 version, on github, with is "pip-packageable"
(but not on pypi ... need more tests yet)

**Comment by bendub** [comment] 2020-01-27 11:50
Thanks Manatlan.
I'll try it tomorrow.

**Comment by manatlan** [comment] 2020-01-27 16:53
the 0.4.0 is out, on pypi ... should fix this issue
I close it

**Closed by manatlan** 2020-01-27 16:53 UTC
Labels: bug

**Comment by bendub** [comment] 2020-01-29 13:01
Sorry for the late.
I packaged my app using poetry and I have the same problem again.

**Comment by manatlan** [comment] 2020-01-29 14:11
In your case : perhaps you should change your static folder ... because it seems that you have prefixed it with "ui" (set guy.FOLDERSTATIC = "ui/static") ...

what the msg ?

**Comment by bendub** [comment] 2020-01-29 14:34
To avoid problem, following your advice, I move 'static' directory in "myapp/myapp/static".
The error reported in my browser is:
> ERROR: can't find '/home/USER/.../cloc_venv/bin/static/ClocGui.html'
It seems it look for 'static' directory in the place where '__name__==__main__'
PS : I test my project in a virtualenv

**Comment by manatlan** [comment] 2020-01-29 14:53
You're right .. I've got the same kind of troubles, when using venv place (with poetry shell) ...
So I was doing all my tests without using venv ....

If you look :
https://github.com/manatlan/guy/blob/98c41e3a48f7f99dbcf1666e7b0431797c112480/guy.py#L65
It's the way it (try) to resolv where static sits ...

In fact, it will certainly work for you if you release your whl, and install it ... and execute from package.

I really need to found a new (AND SIMPLE) way to resolv this things, in all cases ...
(In my the "old guy" : wuy ... devs needed to set a "wuy.path" to specify where static were ... and I don't want to do that in "guy" ...)

**Comment by manatlan** [comment] 2020-01-31 12:27
Please ... try the new "0.4.1" ...
It will be able to find the "static" associated with the class, in all cases ... and it should work, as expected, using venv too

**Comment by bendub** [comment] 2020-01-31 17:37
It works! Thanks you Manatlan.
I can access my UI now.
However I had errors when I play with the config.json file. But I need to test more, perhaps the problem is from my side.

**Comment by manatlan** [comment] 2020-01-31 22:49
With 0.4.1 there were trouble with config...
The 0.4.2 seems ok for me
